/*
===============================================================================
Advanced Business Intelligence & Analytics Queries: E-Commerce Datamart
===============================================================================
Script Purpose:
    This script contains 22 advanced analytical queries leveraging the cleaned 
    e-commerce datamart schema ('ec_datamart'). It delivers deep operational, 
    financial, and behavioral insights including product performance, customer 
    segmentation, cohort retention, supply chain logistics, and web traffic.

Key Techniques Used:
    - Common Table Expressions (CTEs)
    - Window Functions (ROW_NUMBER, LAG, RANK, NTILE, Cumulative SUM/AVG)
    - Date Manipulation & Cohort Indexing
    - Aggregations and Conditional Business Logic
===============================================================================
*/

USE ECOMDB;
GO

/*
===============================================================================
SECTION 1: PRODUCT & CATEGORY PERFORMANCE
===============================================================================
*/

-- 1. Total revenue generated by each product category hierarchy
-- Purpose: Evaluates top-performing product categories to guide merchandising strategy.
SELECT 
    p.category_hierarchy,
    SUM(o.total_amount) AS revenue
FROM ec_datamart.clean_products_inventory AS p
LEFT JOIN ec_datamart.clean_orders AS o
    ON p.prod_id = o.product_id
GROUP BY p.category_hierarchy
ORDER BY revenue DESC;


-- 2. Top 5 highest-grossing products across the catalog
-- Purpose: Identifies high-value inventory items driving maximum revenue.
SELECT TOP 5 
    p.product_name,
    SUM(o.total_amount) AS revenue
FROM ec_datamart.clean_products_inventory AS p
LEFT JOIN ec_datamart.clean_orders AS o
    ON p.prod_id = o.product_id
GROUP BY p.product_name
ORDER BY revenue DESC;


-- 3. Dead stock / Zero-sale products identified for inventory optimization
-- Purpose: Flags items with zero recorded sales to manage holding costs and dead stock.
SELECT 
    p.product_name,
    SUM(o.total_amount) AS revenue
FROM ec_datamart.clean_products_inventory AS p
LEFT JOIN ec_datamart.clean_orders AS o
    ON p.prod_id = o.product_id
GROUP BY p.product_name
HAVING SUM(o.total_amount) IS NULL OR SUM(o.total_amount) = 0
ORDER BY revenue ASC;


/*
===============================================================================
SECTION 2: CUSTOMER SEGMENTATION & BEHAVIOR
===============================================================================
*/

-- 4. Top-selling product per city using window functions (ROW_NUMBER)
-- Purpose: Identifies regional product preferences for localized marketing campaigns.
WITH cte_city AS (
    SELECT 
        c.city,
        p.product_name,
        p.category_hierarchy,
        SUM(o.total_amount) AS revenue
    FROM ec_datamart.clean_products_inventory AS p
    JOIN ec_datamart.clean_orders AS o
        ON p.prod_id = o.product_id
    JOIN ec_datamart.clean_customers AS c
        ON c.cust_id = o.customer_id
    GROUP BY c.city, p.product_name, p.category_hierarchy
),
cte_ranked_city AS (
    SELECT 
        city,
        product_name,
        category_hierarchy,
        revenue,
        ROW_NUMBER() OVER (PARTITION BY city ORDER BY revenue DESC) AS rn
    FROM cte_city
)
SELECT 
    city,
    product_name,
    category_hierarchy,
    revenue
FROM cte_ranked_city
WHERE rn = 1;


-- 5. Top product categories generating revenue specifically among GOLD and PLATINUM tier customers
-- Purpose: Analyzes purchasing preferences of high-value loyalty customers.
WITH cte_loyalty AS (
    SELECT 
        c.loyalty_tier,
        p.category_hierarchy,
        SUM(o.total_amount) AS revenue
    FROM ec_datamart.clean_products_inventory AS p
    JOIN ec_datamart.clean_orders AS o
        ON p.prod_id = o.product_id
    JOIN ec_datamart.clean_customers AS c
        ON c.cust_id = o.customer_id
    GROUP BY c.loyalty_tier, p.category_hierarchy
)
SELECT 
    loyalty_tier,
    category_hierarchy,
    revenue
FROM cte_loyalty
WHERE loyalty_tier IN ('GOLD', 'PLATINUM')
ORDER BY revenue DESC;


/*
===============================================================================
SECTION 3: TIME-SERIES & REVENUE TRENDS
===============================================================================
*/

-- 6. Month-over-Month (MoM) revenue growth analysis using LAG window function
-- Purpose: Tracks business growth velocity and month-over-month fluctuations.
WITH cte_month AS (     
    SELECT 
        DATENAME(MONTH, o.order_date) AS months,
        SUM(o.total_amount) AS revenue,
        YEAR(o.order_date) AS order_year,
        MONTH(o.order_date) AS month_num
    FROM ec_datamart.clean_products_inventory AS p
    JOIN ec_datamart.clean_orders AS o
        ON p.prod_id = o.product_id
    GROUP BY MONTH(o.order_date), YEAR(o.order_date), DATENAME(MONTH, o.order_date)
)
SELECT 
    months,
    revenue,
    LAG(revenue, 1) OVER (ORDER BY order_year, month_num) AS previous_revenue,
    (revenue - LAG(revenue, 1) OVER (ORDER BY order_year, month_num)) AS dif_revenue
FROM cte_month;


-- 7. Elapsed time (days) between consecutive customer purchases using LAG
-- Purpose: Measures customer purchase frequency and retention intervals.
WITH cte_customers AS (
    SELECT 
        c.cust_id,
        o.order_date,
        SUM(o.total_amount) AS revenue
    FROM ec_datamart.clean_orders AS o
    RIGHT JOIN ec_datamart.clean_customers AS c
        ON c.cust_id = o.customer_id
    GROUP BY c.cust_id, o.order_date
)
SELECT 
    cust_id,
    order_date,
    LAG(order_date, 1) OVER (PARTITION BY cust_id ORDER BY order_date ASC) AS previous_day,
    DATEDIFF(day, LAG(order_date, 1) OVER (PARTITION BY cust_id ORDER BY order_date ASC), order_date) AS days_btw_orders,
    revenue
FROM cte_customers;


-- 8. Customer Lifetime Value (LTV) segmentation based on total historical spend
-- Purpose: Re-segments customers into computed tier bands based on aggregate spending.
WITH cte_expenditure AS (
    SELECT 
        c.cust_id,
        c.loyalty_tier,
        SUM(o.total_amount) AS total_spend
    FROM ec_datamart.clean_orders AS o
    RIGHT JOIN ec_datamart.clean_customers AS c
        ON c.cust_id = o.customer_id
    GROUP BY c.cust_id, c.loyalty_tier
)
SELECT 
    cust_id,
    total_spend,
    CASE
        WHEN total_spend < 500 THEN 'VIP'
        WHEN total_spend BETWEEN 500 AND 1000 THEN 'GOLD'
        WHEN total_spend BETWEEN 1000 AND 2500 THEN 'STANDARD'
        ELSE 'DIAMOND'
    END AS computed_ltv_tier
FROM cte_expenditure
ORDER BY total_spend DESC;


-- 9. Running total (cumulative revenue) per customer over time
-- Purpose: Visualizes cumulative financial contribution of individual customers.
WITH cte_cumulative AS (
    SELECT 
        c.cust_id,
        YEAR(o.order_date) AS years,
        DATENAME(MONTH, o.order_date) AS months,
        SUM(o.total_amount) AS revenue,
        MONTH(o.order_date) AS month_num
    FROM ec_datamart.clean_customers AS c
    LEFT JOIN ec_datamart.clean_orders AS o
        ON c.cust_id = o.customer_id
    WHERE o.order_date IS NOT NULL
    GROUP BY c.cust_id, DATENAME(MONTH, o.order_date), YEAR(o.order_date), MONTH(o.order_date)
)
SELECT 
    cust_id,
    months,
    SUM(revenue) OVER (
        PARTITION BY cust_id 
        ORDER BY years, month_num 
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS cumulative_revenue
FROM cte_cumulative;


-- 10. Three-month moving average revenue per customer
-- Purpose: Smooths out monthly revenue volatility to identify purchasing trends.
WITH cte_avg AS (
    SELECT 
        c.cust_id,
        YEAR(o.order_date) AS years,
        DATENAME(MONTH, o.order_date) AS months,
        SUM(o.total_amount) AS revenue,
        MONTH(o.order_date) AS month_num
    FROM ec_datamart.clean_customers AS c
    LEFT JOIN ec_datamart.clean_orders AS o
        ON c.cust_id = o.customer_id
    WHERE o.order_date IS NOT NULL
    GROUP BY c.cust_id, DATENAME(MONTH, o.order_date), YEAR(o.order_date), MONTH(o.order_date)
)
SELECT 
    cust_id,
    months,
    AVG(revenue) OVER (
        PARTITION BY cust_id 
        ORDER BY years, month_num 
        ROWS BETWEEN 2 PRECEDING AND CURRENT ROW
    ) AS moving_avg_revenue
FROM cte_avg;


-- 11. Top spenders ranked by month using RANK window function
-- Purpose: Identifies leading monthly spenders for targeted promotions.
WITH cte_spenders AS (
    SELECT 
        c.cust_id,
        DATENAME(MONTH, o.order_date) AS months,
        SUM(o.total_amount) AS total_expense,
        MONTH(o.order_date) AS month_num,
        YEAR(o.order_date) AS year_num
    FROM ec_datamart.clean_customers AS c
    LEFT JOIN ec_datamart.clean_orders AS o
        ON c.cust_id = o.customer_id
    WHERE o.order_date IS NOT NULL
    GROUP BY c.cust_id, DATENAME(MONTH, o.order_date), YEAR(o.order_date), MONTH(o.order_date)
)
SELECT 
    cust_id,
    months,
    total_expense,
    RANK() OVER (PARTITION BY year_num, month_num ORDER BY total_expense DESC) AS spending_rank
FROM cte_spenders;


-- 12. Customer spending quartiles using NTILE bucket analysis
-- Purpose: Segments customer base into 4 equal tiers based on aggregate order volume.
WITH cte_quartiles AS (
    SELECT 
        o.customer_id,
        SUM(o.total_amount) AS spending
    FROM ec_datamart.clean_customers AS c
    LEFT JOIN ec_datamart.clean_orders AS o
        ON c.cust_id = o.customer_id
    GROUP BY o.customer_id
)
SELECT 
    customer_id,
    spending, 
    NTILE(4) OVER (ORDER BY spending DESC) AS spending_quartile
FROM cte_quartiles;


/*
===============================================================================
SECTION 4: COHORT ANALYSIS
===============================================================================
*/

-- 13. Finding customer first-purchase acquisition cohorts
-- Purpose: Isolates the initial transaction date for every customer.
WITH cte_cohorts AS (
    SELECT 
        o.customer_id,
        o.order_date,
        DATENAME(MONTH, o.order_date) AS months,
        ROW_NUMBER() OVER (PARTITION BY customer_id ORDER BY order_date ASC) AS rn
    FROM ec_datamart.clean_customers AS c
    LEFT JOIN ec_datamart.clean_orders AS o
        ON c.cust_id = o.customer_id
    WHERE o.order_date IS NOT NULL
)
SELECT 
    customer_id,
    order_date AS acquisition_date,
    months
FROM cte_cohorts
WHERE rn = 1;


-- 14. Calculating retention cohort index (months since first purchase)
-- Purpose: Tracks customer engagement timeline relative to their signup month.
WITH cte_first_order AS (
    SELECT 
        customer_id,
        MIN(order_date) AS first_order_date
    FROM ec_datamart.clean_orders
    WHERE order_date IS NOT NULL
    GROUP BY customer_id
),
cte_cohort_index AS (
    SELECT 
        o.customer_id,
        o.order_date,
        f.first_order_date,
        DATEDIFF(month, f.first_order_date, o.order_date) AS cohort_index
    FROM ec_datamart.clean_orders AS o
    JOIN cte_first_order AS f
        ON o.customer_id = f.customer_id
)
SELECT 
    customer_id,
    first_order_date,
    order_date,
    cohort_index,
    CASE 
        WHEN cohort_index = 0 THEN 'Month 0 (Signup)'
        WHEN cohort_index = 1 THEN 'Month 1'
        WHEN cohort_index = 2 THEN 'Month 2'
        WHEN cohort_index = 3 THEN 'Month 3'
        ELSE 'Month 4+'
    END AS cohort_label
FROM cte_cohort_index;


/*
===============================================================================
SECTION 5: INVENTORY & SUPPLY CHAIN LOGISTICS
===============================================================================
*/

-- 15. Inventory valuation & capital tied up per product category
-- Purpose: Calculates total monetary value of current stock holding per category.
SELECT 
    category_hierarchy,
    SUM(stock_count * cost_price) AS total_stock_valuation
FROM ec_datamart.clean_products_inventory
GROUP BY category_hierarchy
ORDER BY total_stock_valuation DESC;


-- 16. Dead stock inventory audit (Products with zero sales history)
-- Purpose: Highlights catalog items that have never been purchased.
SELECT 
    p.product_name,
    p.category_hierarchy,
    p.stock_count
FROM ec_datamart.clean_products_inventory AS p
LEFT JOIN ec_datamart.clean_orders AS o
    ON p.prod_id = o.product_id
WHERE o.order_id IS NULL;


-- 17. Products ranked by total website traffic engagement vs stock count
-- Purpose: Correlates user browsing interest with available inventory.
SELECT 
    p.product_name,
    COUNT(w.event_id) AS total_events,
    p.stock_count
FROM ec_datamart.clean_products_inventory AS p
JOIN ec_datamart.clean_website_events AS w
    ON p.prod_id = w.new_product_id
GROUP BY p.product_name, p.stock_count
ORDER BY total_events DESC;


-- 18. Shipping fulfillment duration performance by carrier
-- Purpose: Measures carrier delivery speed and fulfillment efficiency.
SELECT 
    carrier,
    AVG(actual_days_to_deliver) AS avg_delivery_days
FROM ec_datamart.clean_shipping_logs
GROUP BY carrier;


-- 19. Shipping status breakdown profile
-- Purpose: Summarizes shipment milestone distributions.
SELECT 
    status_log_clean,
    COUNT(order_ref) AS no_orders
FROM ec_datamart.clean_shipping_logs
GROUP BY status_log_clean;


-- 20. Delayed shipments count and tracking breakdown by carrier
-- Purpose: Identifies logistics bottlenecks and carrier delay frequencies.
SELECT 
    carrier,
    COUNT(order_ref) AS delayed_orders_count
FROM ec_datamart.clean_shipping_logs
WHERE (actual_days_to_deliver - estimated_days_to_deliver) > 0
GROUP BY carrier
ORDER BY delayed_orders_count DESC;


/*
===============================================================================
SECTION 6: WEBSITE TRAFFIC & USER EXPERIENCE (UX)
===============================================================================
*/

-- 21. Traffic source performance breakdown by event volume
-- Purpose: Evaluates marketing channel effectiveness and user acquisition touchpoints.
SELECT 
    traffic_source,
    COUNT(event_id) AS event_id_count
FROM ec_datamart.clean_website_events 
GROUP BY traffic_source
ORDER BY event_id_count DESC;


-- 22. Device type and Operating System (OS) visit breakdown
-- Purpose: Analyzes technical platform preferences of site visitors.
SELECT 
    device_type,
    os,
    COUNT(visitor_id) AS visits
FROM ec_datamart.clean_website_events 
GROUP BY device_type, os
ORDER BY visits DESC;
